spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 7a53c7593fb2ca88c9d7
            client-secret: ba1fe647ce076408f152867afe84fe82687137cf


#logging:
#  level:
#    org.springframework.security: DEBUG
