server:
  port: 8080

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: beans, env, health, info

spring:
  jackson:
    default-property-inclusion: NON_ABSENT
  datasource:
    url: jdbc:postgresql://192.168.1.100:5432/postgres
    username: postgres
    password: 123456
    driver-Class-Name: org.postgresql.Driver
    hikari:
      pool-name: DVDRENTAL_DB-CONN-POOL
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 240000  # 4 min
      connection-timeout: 2000  # 2 sec
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        jdbc:
          time_zone: UTC
        temp:
          use_jdbc_metadata_defaults: false  # Disables / prevents HHH000424: Disabling contextual LOB creation as createClob() method threw error
  h2:
    console:
      enabled: true
