###
POST http://localhost:8080/auth/register?first_name=billyfirst&last_name=li&user_name=billyusername&email=billy@test.com&password=123456



###
POST http://localhost:8080/auth/login?user_name=billyli&password=123456

###
POST http://localhost:8080/auth/login?user_name=billyusername&password=123456

###
GET  http://localhost:8080/user
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiaWxseXVzZXJuYW1lIiwiaWF0IjoxNjUzMTY5OTMxLCJleHAiOjE2NTMxODc5MzF9.wV_kTXKRiBfFgemcGPQenPI0PxjifTyE0hQg8sxQCEk

